---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - repo_folder_backend: /var/www/backend-deployment/repos/
    - repo_folder_frontend: /var/www/frontend-deployment/repos/
    - live_folder: /var/www/my_app/build
    - repo_name_backend: Bash-mocart/gbh-api
    - repo_name_frontend: Bash-mocart/gbh-app


  pre_tasks:
    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  roles:
    - deploy-web-api
    - deploy-web-app
  