version: "3.9"
services:
  api:
    restart: always
    image: node:16.18.1-bullseye-slim 
    volumes:
      - ./gbh-api:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start
    environment:
      - API_PORT=3001
    ports:
      - 3001:3001
      
  web:
    restart: always
    image: node:16.18.1-bullseye-slim 
    volumes:
      - ./gbh-app:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    ports:
      - 80:3000
    
  database:
    restart: always
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local
    
    
    