version: "3"
services:
  default-lb:
    restart: "always"
    image: bashox/onedot:v1
    depends_on:
      - app1
      - app2
    ports:
      - 8888:80
  app1:
    restart: "always"
    image: bashox/onedotapp:v5bullseye
    user: 0:0
    environment:
      - PORT=1111
    
  app2:
    restart: "always"
    image: bashox/onedotapp:v5bullseye
    user: 0:0
    environment:
      - PORT=2222
