---
- name: Creates directory n
  file:
    path: ~/web-app
    state: directory
  
- name: Unarchive Web App
  unarchive:
    src: demo-webapp-main.gz
    dest: ~/web-app
  
- name: "start app"
  shell: |       
      pm2 serve build 3000
  args: 
    chdir: ~/web-app/demo-webapp-main

- name: "List processes"
  shell: |      
      pm2 list
  register: pm2_result 

- name: "Print in the debug console"
  debug:
    var: pm2_result.stdout_lines

 
 





     

    