---
  
- name: Unarchive Web App
  unarchive:
    src: demo-webapp-main.gz
    dest: "{{ repo_folder_frontend }}"
  
- name: "start app"
  shell: |       
      pm2 serve build 3000 -f
  args: 
    chdir: "{{ repo_folder_frontend }}"

- name: "List processes"
  shell: |      
      pm2 list
  register: pm2_result 

- name: "Print in the debug console"
  debug:
    var: pm2_result.stdout_lines

 
 





     

    