pipeline {
    agent any

    stages {
        stage('checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/Bash-mocart/gbh.git'
            }
        }
        stage('Install Web Api') {
            when { changeset "demo-api-main/*"}
            steps {
                sh 'npm install'
            }
        }

        stage('Install Web App') {
            when { changeset "demo-webapp-main/*"}
            steps {
                sh 'npm install'
            }
        }

        stage('Build Web Api'){
            when { changeset "demo-api-main/*"}
            steps {
                sh 'npm run build'
            }
        }

        stage('Build Web App'){
            when { changeset "demo-webapp-main/*"}
            steps {
                sh 'npm run build'
            }
        }

        stage (' PR check ') {
            when {
                branch 'PR-*'  
            }
            steps {
            sh 'ansible-playbook deploy-backend.yml -i inventory.txt'
            }

        }
        
    }
}