---
- name: Unarchive Web App
  unarchive:
    src: demo-api-main.gz
    dest: "{{ repo_folder_backend }}"

- name: "start app"
  shell: |       
      pm2 start npm -f ./app.js -- run start
  args: 
    chdir: "{{ repo_folder_backend }}"

- name: "List processes"
  shell: |      
      pm2 list
  register: pm2_result 

- name: "Print in the debug console"
  debug:
    var: pm2_result.stdout_lines
 
 





     

    