---
- name: Creates directory n
  file:
    path: ~/web-api
    state: directory

- name: Unarchive Web App
  unarchive:
    src: demo-api-main.gz
    dest: ~/web-api

- name: "start app"
  shell: |       
      pm2 start npm -f ./app.js -- run start
  args: 
    chdir: ~/web-api/demo-api-main

- name: "List processes"
  shell: |      
      pm2 list
  register: pm2_result 

- name: "Print in the debug console"
  debug:
    var: pm2_result.stdout_lines
 
 





     

    